#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

cd /app/sonarr/bin || exit

redirect_cmd exec s6-setuidgid abc \
	mono --debug Sonarr.exe \
	-nobrowser -data=/config
