#!/usr/bin/with-contenv bash

umask ${UMASK_SET:-022}

redirect_cmd() {
	if [[ "${DEBUG}" == "true" ]]; then
		"$@"
	else
		"$@" >/dev/null 2>&1
	fi
}

cd /app/sonarr/bin || exit

echo "Starting Sonarr."
redirect_cmd exec s6-setuidgid abc \
	mono --debug Sonarr.exe \
	-nobrowser \
	-data=/config
